joint_position_controller:
    type: franka_ros_controllers/JointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

effort_joint_position_controller:
    type: franka_ros_controllers/EffortJointPositionController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k_gains:
        - 1200.0
        - 1000.0
        - 1000.0
        - 800.0
        - 300.0
        - 200.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    publish_rate: 30.0

joint_velocity_controller:
    type: franka_ros_controllers/JointVelocityController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

joint_torque_controller:
    type: franka_ros_controllers/JointTorqueController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

joint_impedance_controller:
    type: franka_ros_controllers/JointImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k_gains: # if changing the default values, remember to change in the cfg file as well
        - 120.0
        - 100.0
        - 100.0
        - 80.0
        - 30.0
        - 20.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    publish_rate: 30.0
    coriolis_factor: 1.0 

cartesian_pose_controller:
    type: franka_ros_controllers/CartesianPoseController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

cartesian_velocity_controller:
    type: franka_ros_controllers/CartesianVelocityController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

cartesian_impedance_controller:
    type: franka_ros_controllers/CartesianImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    stiffness_gains:
        - 200.0
        - 200.0
        - 200.0
        - 20.0
        - 20.0
        - 20.0

force_controller:
    type: franka_ros_controllers/ForceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

